# GrowDesk V2 Docker Compose
version: '3.8'

services:
  # Backend Go Service
  backend:
    build:
      context: ./GrowDesk/backend
      dockerfile: Dockerfile
    container_name: growdesk-backend
    ports:
      - "8080:8080"
    volumes:
      - ./GrowDesk/backend/data:/app/data
    environment:
      - PORT=8080
      - DATA_DIR=/app/data
      - MOCK_AUTH=true
    restart: unless-stopped
    networks:
      - grow-network

  # Frontend Service (Panel de Administración)
  frontend:
    build:
      context: ./GrowDesk/frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: growdesk-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./GrowDesk/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080/api
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - grow-network
    restart: unless-stopped

  # Widget Core Service
  widget-core:
    build:
      context: ./GrowDesk-Widget/widget-core
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./GrowDesk-Widget/widget-core:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3030
    restart: unless-stopped
    networks:
      - grow-network

  # Widget API Service
  widget-api:
    build:
      context: ./GrowDesk-Widget/widget-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./GrowDesk-Widget/widget-api:/app
      - ./GrowDesk-Widget/widget-api/data:/app/data
    environment:
      - PORT=3000
      - GROWDESK_API_URL=http://growdesk-backend:8080
      - GROWDESK_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJhZG1pbi0xMjMiLCJlbWFpbCI6ImFkbWluQGdyb3dkZXNrLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyNDA4ODQwMH0.8J5ayPvA4B-1vF5NaqRXycW1pmIl9qjKP6Ddj4Ot_Cw
      - WIDGET_BASE_URL=http://widget-core:3030
      - WIDGET_API_URL=http://widget-api:3000
      - GIN_MODE=debug
      - JWT_SECRET=clave_secreta_desarrollo_local
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:3030,http://localhost:8090
    restart: unless-stopped
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - grow-network

  # Demo Site
  demo-site:
    build:
      context: ./GrowDesk-Widget/examples/simple-demo
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./GrowDesk-Widget/examples/simple-demo:/app
      - /app/node_modules
    depends_on:
      - widget-core
      - widget-api
    environment:
      - PORT=8090
      - NODE_ENV=development
      - WIDGET_CORE_URL=http://localhost:3030
      - WIDGET_API_URL=http://localhost:3001
    restart: unless-stopped
    networks:
      - grow-network

  postgres:
    image: postgres:15
    container_name: growdesk-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: growdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grow-network

  redis:
    image: redis:7
    container_name: growdesk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - grow-network

networks:
  grow-network:
    driver: bridge

volumes:
  postgres_data:
  backend_uploads: 