# Usa Node.js con Alpine como base
FROM node:18-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Expone el puerto de Vite
EXPOSE 5173

# Usa volumes para evitar copiar node_modules
VOLUME /app/node_modules

# Comando para ejecutar Vite en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
