version: '3.8'

services:
  widget-core:
    build:
      context: ./widget-core
      dockerfile: Dockerfile
    image: growdesk-widget-widget-core
    ports:
      - "5174:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - API_URL=http://widget-api:3000
    volumes:
      - ./widget-core:/app
      - /app/node_modules
    depends_on:
      - widget-api
    restart: unless-stopped

  widget-api:
    build:
      context: ./widget-api
      dockerfile: Dockerfile
    image: growdesk-widget-widget-api
    ports:
      - "8082:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=growdesk_widget
      - GROWDESK_API_URL=http://172.21.0.5:8080
      - GROWDESK_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJhZG1pbi0xMjMiLCJlbWFpbCI6ImFkbWluQGdyb3dkZXNrLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyNDA4ODQwMH0.8J5ayPvA4B-1vF5NaqRXycW1pmIl9qjKP6Ddj4Ot_Cw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    volumes:
      - ./widget-api:/app
      - /app/node_modules
      - ./widget-api/data:/app/data
    restart: unless-stopped
    networks:
      - widget-network
      - growdesk_grow-network

  demo-site:
    build:
      context: ./examples/simple-demo
      dockerfile: Dockerfile
    image: growdesk-widget-demo-site
    ports:
      - "8090:8090"
    volumes:
      - ./examples/simple-demo:/app
      - /app/node_modules
    depends_on:
      - widget-core
      - widget-api
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=growdesk_widget
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  widget-network:
  growdesk_grow-network:
    external: true 