version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: growdesk-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080/api
      - VITE_SYNC_API_URL=http://localhost:8080/api/sync/users
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - grow-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: growdesk-backend
    ports:
      - "8080:8080"
    networks:
      - grow-network
    environment:
      - PORT=8080
      - DATA_DIR=/app/data
      - MOCK_AUTH=true
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  sync-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: growdesk-sync-server
    command: ["go", "run", "cmd/sync-server/main.go"]
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data
      - ./backend/data:/backend/data
    environment:
      - PORT=8000
      - DATA_DIR=/app/data
      - LOCAL_DATA_DIR=/backend/data
    networks:
      - grow-network
    restart: unless-stopped
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: growdesk-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: growdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grow-network

  redis:
    image: redis:7
    container_name: growdesk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - grow-network

networks:
  grow-network:
    driver: bridge

volumes:
  postgres_data:
  backend_data:
  backend_uploads:

