version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: growdesk-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080/api
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - grow-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: growdesk-backend
    ports:
      - "8080:8080"
    networks:
      - grow-network
    environment:
      - PORT=8080
      - DATA_DIR=/app/data
      - MOCK_AUTH=true
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: growdesk-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: growdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grow-network

  redis:
    image: redis:7
    container_name: growdesk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - grow-network

networks:
  grow-network:
    driver: bridge

volumes:
  postgres_data:
  backend_data:
  backend_uploads:

